### ISSUE TITLE
Segmentation fault on failing backwards search

### ISSUE THREAD

**Issue by agacek** [snaptoken/kilo-tutorial#10]
Starting with step 140, if you search for something that doesn't exist and then hit the left arrow, the application segmentation faults. The problem is that `current`, `last_match`, and `direction` are all `-1` so `current` becomes `-2`. The application only checks for `current == -1` for wraparound.

**Comment by yjerem** [comment]
Nice catch, thanks! I fixed it with a line of code from the original `kilo`, which sets `direction` to `1` when `last_match` is `-1`.
