### ISSUE TITLE
Step 20 - clarity needed, else statement removed.

### ISSUE THREAD

**Issue by wonthegame** [snaptoken/kilo-tutorial#13]
For step 20, the else statement to print a carriage return and a newline is removed. This is before the refactor and may confuse some. Up until this point lines were edited and added to but not removed.

**Comment by yjerem** [comment]
Good point. I changed it so that the code is removed in the refactoring step instead, and added "We’ll also stop printing out keypresses at this point." to the text for that step. Hopefully that makes it more clear. Thanks!
