### ISSUE TITLE
Issue in Chapter 3 "editorReadKey" function 

### ISSUE THREAD

**Issue by palerdot** [snaptoken/kilo-tutorial#15]
I was walking through the following code diff
```
char editorReadKey() {
  int nread;
  char c;
  while ((nread = read(STDIN_FILENO, &c, 1)) != 1) {
    if (nread == -1 && errno != EAGAIN) die("read");
  }
  return c;
}
```

And I have to change the **while** loop to an **if** condition to make it work. In fact, the while loop does not seem to break and proceed to the next return statement. I'm not sure if I'm missing something here. Also, before refactoring into this module, the code block was having a if condition as follows

```
char c = '\0';
if (read(STDIN_FILENO, &c, 1) == -1 && errno != EAGAIN) die("read");
```

PS: My C is very rusty. I just would like to know what is that I'm missing here.

Thanks.

**Comment by yjerem** [comment]
`editorReadKey()` is supposed to wait until the user presses a key before returning. So it uses the `while` loop to wait until `read()` returns `1`.

If the program quits when you press `Ctrl-Q`, then it's working properly.

Sorry if that section isn't very clear, it's a pretty complicated step that changes a lot of things at once.

**Comment by palerdot** [comment]
sorry. my mistake. I was trying to change that bit of code to be more readable like I do in other languages by assigning them to separate variables like this

```
int input_read;                                                             
        valid_input_read;

    char c;

    // read the input
    input_read = read(STDIN_FILENO, &c, 1);
    // check if it is a valid input
     valid_input_read = (input_read != 1);

    while (valid_input_read) {
      // didn't work because of the way I have made my assignments
   }
```

I'm not quite comfortable with doing this long assertions in conditions, so I tried to change it without knowing the consequences. Thanks for your response. Nice tutorial btw.

**Comment by yjerem** [comment]
Ah, I see. Maybe a `do...while` loop is what you're looking for:

    do {
      nread = read(STDIN_FILENO, &c, 1);
      if (nread == -1 && errno != EAGAIN) die("read");
    } while (nread != 1);

**Comment by palerdot** [comment]
Thanks. That helped.
