### ISSUE TITLE
Discrepancy between kilo-src and kilo-tutorial?

### ISSUE THREAD

**Issue by timsneath** [snaptoken/kilo-tutorial#23]
It's possible that I'm being really dumb (likely, even?) but I'm seeing a discrepancy between the final source code (propagate-highlight tag) and the code on the website. Here's the difference as it shows in my code:
```
@@ -388,14 +403,15 @@ void editorSelectSyntaxHighlight() {
   E.syntax = NULL;
   if (E.filename == NULL) return;
 
+  char *ext = strrchr(E.filename, '.');
+
   for (unsigned int j = 0; j < HLDB_ENTRIES; j++) {
     struct editorSyntax *s = &HLDB[j];
     unsigned int i = 0;
     while (s->filematch[i]) {
-      char *p = strstr(E.filename, s->filematch[i]);
-      if (p != NULL) {
-        int patlen = strlen(s->filematch[i]);
-        if (s->filematch[i][0] != '.' || p[patlen] == '\0') {
+      int is_ext = (s->filematch[i][0] == '.');
+      if ((is_ext && ext && !strcmp(ext, s->filematch[i])) ||
+          (!is_ext && strstr(E.filename, s->filematch[i]))) {
         E.syntax = s;
```

Note that kilo-src\kilo.c has a reference to an int variable `patlen`, which doesn't seem to show in the description of this function (contained in [section 7](http://viewsourcecode.org/snaptoken/kilo/07.syntaxHighlighting.html)).

**Comment by yjerem** [comment]
You're right! I forgot to update the kilo-src repo after I made that change to the code. I've updated the repo just now. Thanks for letting me know about this! You'll have to reclone the kilo-src repo instead of pulling, as its entire git history gets rewritten whenever I update it.
