### ISSUE TITLE
Missing calls to comment VMIN and VTIME between steps 30 and 32

### ISSUE THREAD

**Issue by mijoharas** [snaptoken/kilo-tutorial#34]
First off, thanks for a great tutorial!

During step 30 and until step 32 where you use `editorReadKey` in order to block so you can observe output before dying, you have forgotten to comment the lines in `enableRawMode`:

```
  /* raw.c_cc[VMIN] = 0; */
  /* raw.c_cc[VTIME] = 1; */
```
Otherwise, the output is only on the screen for 0.1s before the read call returns and the program returns.

**Comment by NieDzejkob** [comment]
That's weird, I didn't encounter this issue when following the tutorial. Note that [`editorReadKey` during those steps](https://github.com/snaptoken/kilo-src/blob/bottom-right/kilo.c#L55-L62) is looping when no bytes are returned with `errno == EAGAIN`.

**Comment by mijoharas** [comment]
Ahhhh... this looks like my problem. I had that line as being an if rather than a `while` loop, must've missed that while messing with some stuff. Loop makes more sense there. Thanks for the help @NieDzejkob
