### ISSUE TITLE
Can't  understand this part! (Step 20)

### ISSUE THREAD

**Issue by f3rn4nd0000** [snaptoken/kilo-tutorial#41]
I'm talking especifically about the bitwise operation:

> The CTRL_KEY macro bitwise-ANDs a character with the value 00011111, in binary.

I'm confuse when it says :

> in other words, it sets the upper 3 bits of the character to 0. This mirrors what the Ctrl key does in the terminal: it strips bits 5 and 6 from whatever key you press in combination with Ctrl, and sends that. The ASCII character set seems to be designed this way on purpose. (It is also similarly designed so that you can set and clear bit 5 to switch between lowercase and uppercase.)

If the ctrl key strips bit 5 and 6 then the bitwise binary operator should've been 01100000 (96) NOT 00011111 (31) am i right?

**Comment by kepair** [comment]
CTRL_KEY performs a [bitwise-AND](https://en.wikipedia.org/wiki/Bitwise_operation#AND) operation to the character. 
Say you have a binary number, the code of letter 'a': 01100001
When pressing Ctrl+a, the binary number sent will be the result:

```
       01100001 (97 in decimal)
(AND)  00011111 
-------------------
       00000001 

```
It's like a mask, keeping only the values where the mask is 1, and discarding anything where the mask is 0.
