### ISSUE TITLE
At the end of chapter 2, ctrl-J and ctrl-K are not shown

### ISSUE THREAD

**Issue by hardfire** [snaptoken/kilo-tutorial#7]
Hi,
I'm following the tutorial on osx 10.12.3

 in the iterm2 terminal.
at the end of chapter-2 everything seems to work as desired, except the ctrl-J and ctrl-K characters aren't printed. 

I have attached my version of kilo.c just to be sure i haven't made an obvious mistake.

I would also be interested on your approach to fix this issue. As of now I am clueless, maybe digging into termios.h could be one option

Code screenshot as github doesn't allow attaching *.c files. I will put it on a pastebin style website if required.
![screen shot 2017-04-07 at 21 49 22](https://cloud.githubusercontent.com/assets/513457/24808493/a1976842-1bdb-11e7-9225-b926a718386f.png)

Thanks for the awesome tutorial btw. It's been nice to learn about canonical and noncanonical mode. never thought of it.

**Comment by yjerem** [comment]
By the way, fixing Ctrl-J and Ctrl-K are not at all required to proceed with the tutorial. But it would be nice to figure out what's going on with them.

**Comment by hardfire** [comment]
Aha! checking iTerm2 mappings helped to find the culprit.
Apparently I had it mapped to something else, though i never used this mapping.

![screen shot 2017-04-08 at 21 55 51](https://cloud.githubusercontent.com/assets/513457/24830465/468fc91e-1ca6-11e7-8d00-1d3fc34f393b.png)

Thanks for the tip. I will close this as well now.
