### ISSUE TITLE
Searching forward and backward adds characters to the prompt buffer

### ISSUE THREAD

**Issue by fmdkdd** [snaptoken/kilo-tutorial#8]
At the end of chapter 6, searching forward and backward using arrow keys does not work.  Instead, the arrows are appended to the prompt buffer.

One way to fix it in `editorPrompt`:
```diff
-    } else if (!iscntrl(c)) {
+    } else if (!iscntrl(c) && c < ARROW_LEFT) {
      if (buflen == bufsize - 1) {
        bufsize *= 2;
        buf = realloc(buf, bufsize);
      }
      buf[buflen++] = c;
      buf[buflen] = '\0';
    }
    if (callback) callback(buf, c);
```

Since we defined arrows to be values 1000..1003, presumably these values return false for `iscntrl`, and we add them to the prompt buf.  The callback still runs, but since the text has changed, it doesn't move anywhere.

**Comment by yjerem** [comment]
Oops, I broke this with yesterday's change to support extended ASCII.

I've updated step 126 to fix it similarly to how you did (I used `c < 128` to make sure `c` is in the range of a `char`).

Thanks a lot for catching this!

**Comment by fmdkdd** [comment]
You're welcome.  And thanks for the great tutorial!  I had a pretty fun evening ;)
