### ISSUE TITLE
Step 62 and 63 don't compile

### ISSUE THREAD

**Issue by agentultra** [snaptoken/kilo-tutorial#9]
Nice guide so far.

A suggestion: these intermediate steps indicate in the code box that the program will fail to compile at these steps but the text doesn't make a clear indication that this is what we expect and will fix in the subsequent steps.

Could be helpful to mention that we're going to break the program for a few steps.

**Comment by yjerem** [comment]
That's a good point, I've added a note to the text saying it won't compile for those steps. Thanks!
